# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    schema: classpath:schema.sql
    data: classpath:data.sql
#logging:
#  level:
#   root: debug