# 多数据源配置
mybatis-flex:
  datasource:
    ds1-datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
      username: sa
      password:
      schema-locations: classpath:ds1-schema.sql
      data-locations: classpath:ds1-data.sql
    ds2-datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
      username: sa
      password:
      schema-locations: classpath:ds2-schema.sql
      data-locations: classpath:ds2-data.sql