# DataSource Config
spring:
  datasource:
    #driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:memory:myDb;create=true
    username: sa
    password:
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
   root: debug